baseURL = 'https://www.kelvinism.com/'
languageCode = 'en-us'
title = "Kelvin Nicholson"
ignoreLogs = ['warning-partial-superfluous-prefix']

[permalinks]
posts = "/:year/:month/:title"


[params]
disableSpecial1stPost = true
ShowReadingTime = true
ShowBreadCrumbs = false
defaultTheme = "light"
ShowPostNavLinks = false

[markup.goldmark.renderHooks.image]
  useEmbedded = "never"

[markup.goldmark.renderHooks.link]
  useEmbedded = "never"